### ISSUE TITLE
مدیریت چند اپلیکیشن در داشبورد چابک

### ISSUE THREAD

**Issue by tahlilgar** [chabok-io/chabok-panel#1]
سلام وقت بخیر
چطور میشه چنتا اپلیکیشن رو توی داشبورد چابک مدیریت کرد؟ 
باید برای هر اپلیکیشن یک حساب کاربری ساخته بشه؟

**Comment by Husseinhj** [comment]
سلام

باید برای هر اپلیکیشن یک حساب کاربری ساخته بشه؟
بله باید برای هر اپلیکیشن یک پنل جدید ایجاد کنید.
