### ISSUE TITLE
Play store security notification

### ISSUE THREAD

**Issue by Hoss3inf** [chabok-io/chabok-panel#2]
سلام. وقت بخیر
بعد از انتشار برنامه در گوگل پلی، اخطار امنیتی دریافت کرده ام، با متن زیر:

```
Security alert

Your app contains unsafe cryptographic encryption patterns. Please see this [Google Help Center article](https://support.google.com/faqs/answer/9450925) for details.

Vulnerable classes:

com.adpdigital.push.AdpPushClient.encrypt
Affects APK version 10.
```
--------------------

نسخه ی چابک مورد استفاده در برنامه هم به شرح زیر است:
com.adpdigital.push:chabok-lib:2.17.1

لطفا راهنمایی کنید که چطور این هشدار را مدیریت کنم.

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام روز بخیر
<br>
این مورد در نسخه <a href="https://github.com/chabok-io/chabok-client-android/releases/tag/v2.18.2">۲.۱۸.۲</a> برطرف شده
<div>
اگر سوالی بود مجدد ایشو رو باز کنید
<br>
ممنون
</div>
