### ISSUE TITLE
ارسال عکس و صوت

### ISSUE THREAD

**Issue by hoseinjamshidi** [chabok-io/chabok-panel#3]
سلام وقت بخیر
ما از سرویس شما برای ارسال نوتیفیکیشن استفاده میکنیم
الان میخوایم سرویس چت برنامه(ارسال پیام آنی،ارسال عکس و صوت)با استفاده از سرویس شما انجام بدیم
ممنون میشم داکیومنت ایجاد api برام ارسال کنید تا توصعه نرم افزار انجام بدیم
سایت با asp.net core هست و نرم افزار موبایل با Kotlin

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام روز بخیر
<br>
برای ارسال اطلاعات از <a href="https://doc.chabok.io/rest-api/guide.html">سرور به کلاینت</a> و از کلاینتی به کلاینت دیگر می‌تونید از <a href="https://doc.chabok.io/android/push-notification.html">پوش نوتیفیکیشن</a> و یا  <a href="https://doc.chabok.io/android/chabok-messaging.html">پیام چابک</a> استفاده کنید.

برای ارسال عکس و صوت باید در بخش پی‌لود پیام‌ها اطلاعات لازم را برای کلاینت ارسال کنید و خودتون این اطلاعات رو سمت کلاینت هندل کنید و نمایش بدید.

برای اطلاعات بیشتر در مورد سایر کلاینت‌ها به <a href="https://doc.chabok.io/">مستندات</a> مراجعه کنید.
</div>
