### ISSUE TITLE
غیر فعال بودن دکمه دانلود اندروید برای راه اندازی هوشمند

### ISSUE THREAD

**Issue by ahmadina** [chabok-io/chabok-panel#5]
وقت بخیر
در پنل ما دکمه راه اندازی هوشمند برای اندروید غیرفعال است.
در هر دو پنل هم سندباکس هم پروداکشن این مشکل هست

ایمیل
info@azinro.com

<img width="832" alt="Screen Shot 2019-11-26 at 10 47 35 AM" src="https://user-images.githubusercontent.com/5356553/69607277-2ef24b80-103a-11ea-9074-12d04d603c9e.png">

**Comment by hasanghasemzadeh** [comment]
سلام وقت شما هم بخیر

**Comment by farbod-s** [comment]
<div dir="rtl">
سلام روزبخیر
<br>
بزودی روی تمام پنل‌ها فعال میشه
<br>
@ahmadina 
تمایل دارید فایل‌ها رو براتون ایمیل کنم؟
</div>

**Comment by farbod-s** [comment]
<div dir="rtl">
@ahmadina الان باید از توی پنل بتونید دانلود کنید
<br>
اگر مشکلی بود بفرمایید فعلا issue رو میبندم
<div>
